COLORS = {
    "window_bg": "#07111f",
    "panel_bg": "#0b172b",
    "panel_bg_2": "#0d182a",
    "panel_header": "#121d31",
    "panel_border": "#1f2d46",
    "text_main": "#e7edf8",
    "text_soft": "#b8c4d9",
    "text_muted": "#8d9ab3",
    "purple": "#9b4dff",
    "purple_dark": "#251946",
    "purple_hover": "#321b63",
    "blue": "#39a2ff",
    "green": "#32d17d",
    "yellow": "#d9a928",
    "red": "#ff3860",
    "pink": "#ff3e8a",
    "cyan": "#25d8ff",
    "gray": "#8792a8",
}

CATEGORY_ICONS = {
    "access_requests": "◇",
    "documents_finance": "▣",
    "external_requests": "◎",
    "hardware": "⬡",
    "hr_admin": "⌘",
    "internal_info": "☷",
    "monitoring_alerts": "✧",
    "other": "▢",
    "software_errors": "◉",
    "spam_phishing": "⊙",
    "unreadable": "□",
    "urgent_incidents": "△",
}
